# Generated by Django 4.0.2 on 2022-02-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image_alter_listing_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='starting_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='highest_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
