# Generated by Django 4.0.2 on 2022-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bids',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(related_name='listing_bids', to='auctions.Bid'),
        ),
    ]
